version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: docker2/Dockerfile
    container_name: app
    ports:
      - "4200:80"
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/lectureconnect
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: blablabla!!#
      SPRING_JPA_DATABASE: MYSQL
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mysql
    networks:
      - app-network
    volumes:
      - /etc/nginx/sites-available/lecture-connect:/etc/nginx/sites-available/lecture-connect # Mount the Nginx config from VM

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: blablabla!!#
      MYSQL_DATABASE: lectureconnect
      MYSQL_USER: user
      MYSQL_PASSWORD: blablabla??#
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
