-- users
INSERT INTO USERX (ENABLED,FIRST_NAME,LAST_NAME,PASSWORD,USERNAME,EMAIL,CREATE_USER_USERNAME,CREATE_DATE)VALUES(TRUE,'Admin','Istrator','$2a$10$TfySssuPsjcaILwgdB403O2lOCXTS8m1pLy6sONcXDS9xXmkD8dx6','admin','admin@memori.com','admin','2016-01-01 00:00:00')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES)VALUES ('admin', 'ADMIN')
INSERT INTO USERX (ENABLED,FIRST_NAME,LAST_NAME,PASSWORD,USERNAME,EMAIL,CREATE_USER_USERNAME,CREATE_DATE)VALUES(TRUE,'Susi','Kaufgern','$2a$10$TfySssuPsjcaILwgdB403O2lOCXTS8m1pLy6sONcXDS9xXmkD8dx6','user1','susi.kaufgern@memori.com','admin','2016-01-01 00:00:00')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES)VALUES ('user1', 'USER')
INSERT INTO USERX (ENABLED,FIRST_NAME,LAST_NAME,PASSWORD,USERNAME,EMAIL,CREATE_USER_USERNAME,CREATE_DATE)VALUES(TRUE,'Max','Mustermann','$2a$10$TfySssuPsjcaILwgdB403O2lOCXTS8m1pLy6sONcXDS9xXmkD8dx6','user2','max.mustermann@memori.com','admin','2016-01-01 00:00:00')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES)VALUES ('user2', 'USER')
INSERT INTO USERX (ENABLED,FIRST_NAME,LAST_NAME,PASSWORD,USERNAME,EMAIL,CREATE_USER_USERNAME,CREATE_DATE)VALUES(TRUE,'Elvis','The King','$2a$10$TfySssuPsjcaILwgdB403O2lOCXTS8m1pLy6sONcXDS9xXmkD8dx6','elvis','elvis@memori.com','elvis','2016-01-01 00:00:00')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES)VALUES ('elvis', 'ADMIN')

-- rooms
INSERT INTO ROOM (ID,CAPACITY,COMPUTERS_AVAILABLE)VALUES('HS A', 450, FALSE)
INSERT INTO ROOM (ID,CAPACITY,COMPUTERS_AVAILABLE)VALUES('Rechnerraum 22', 30, True)